<?php


return
    array(
        [
            'model_type' => 'Eutranet\Frontend\Models\Page',
            'model_id' => '1',
            'uuid' => '18fb7848-ae44-44e7-8d07-9bb0bcf6f240',
            'collection_name' => 'pages',
            'name' => 'dummy',
            'file_name' => 'dummy.jpg',
            'mime_type' => 'application/x-empty',
            'disk' => 'public',
            'conversions_disk' => 'public',
            'size' => '0',
            'manipulations' => '[]',
            'custom_properties' => '{"mime-type": "image/jpeg"}',
            'generated_conversions' => '[]',
            'responsive_images' => '[]',
            'order_column' => '1',
            'created_at' => '2022-02-18 13:45:24',
            'updated_at' => '2022-02-18 13:45:24',
        ],
        [
            'model_type' => 'Eutranet\Frontend\Models\Page',
            'model_id' => '1',
            'uuid' => 'adecfcbb-828b-4def-a8a3-092b2e5ac2f0',
            'collection_name' => 'pages',
            'name' => 'page',
            'file_name' => 'page.jpg',
            'mime_type' => 'application/x-empty',
            'disk' => 'public',
            'conversions_disk' => 'public',
            'size' => '0',
            'manipulations' => '[]',
            'custom_properties' => '{"mime-type": "image/jpeg"}',
            'generated_conversions' => '[]',
            'responsive_images' => '[]',
            'order_column' => '2',
            'created_at' => '2022-02-18 13:46:20',
            'updated_at' => '2022-02-18 13:46:20',
        ],
        [
            'model_type' => 'App\Models\User',
            'model_id' => '1',
            'uuid' => '1a8d99f0-8164-4e0f-8ac5-38eda14f233c',
            'collection_name' => 'users',
            'name' => 'florbela-oliveira-pg7a0swf35j1hdqkhxvcbmduof4aptp3iobiockm14',
            'file_name' => 'back.jpeg',
            'mime_type' => 'image/jpeg',
            'disk' => 'public',
            'conversions_disk' => 'public',
            'size' => '219955',
            'manipulations' => '[]',
            'custom_properties' => '[]',
            'generated_conversions' => '[]',
            'responsive_images' => '[]',
            'order_column' => '3',
            'created_at' => '2022-02-21 23:25:18',
            'updated_at' => '2022-02-21 23:25:18',
        ],
        [
            'model_type' => 'App\Models\User',
            'model_id' => '2',
            'uuid' => '28ea2087-1ed1-4653-a467-9197f9dfb6d3',
            'collection_name' => 'users',
            'name' => 'image',
            'file_name' => 'maria.jpeg',
            'mime_type' => 'image/jpeg',
            'disk' => 'public',
            'conversions_disk' => 'public',
            'size' => '72628',
            'manipulations' => '[]',
            'custom_properties' => '[]',
            'generated_conversions' => '[]',
            'responsive_images' => '[]',
            'order_column' => '4',
            'created_at' => '2022-02-21 23:55:21',
            'updated_at' => '2022-02-21 23:55:21',
        ],
    );
